server:
  port: 8087

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:sqlserver://${DB_HOST}:14330;databaseName=InventoryDB;encrypt=true;trustServerCertificate=true
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: rabbitmq.rabbitmq.svc.cluster.local   # THAY = TÊN SERVICE THẬT
    port: 5672
    username: testuser
    password: testpass
    virtual-host: /
    connection-timeout: 5000

logging:
  level:
    org.springframework.amqp: DEBUG
    com.rabbitmq: DEBUG
    intern.lp: DEBUG

management:
  endpoint:
    health:
      show-details: always
  health:
    rabbit:
      enabled: true
