server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ProductDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: Root1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-read-timeout: 5000
    eureka-server-connect-timeout: 5000
  instance:
    prefer-ip-address: true
