server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:sqlserver://192.168.0.127:1433;databaseName=ProductDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: Root1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  spring:
   redis:
     host: redis-sentinel-node-0.redis-sentinel-headless.storage-redis.svc.cluster.local
     port: 6379
     password: redispsswd
  cache:
    type: redis


